import { svelte } from '@sveltejs/vite-plugin-svelte';
import { svelteTesting } from '@testing-library/svelte/vite';
import { defineConfig } from 'vitest/config';

export default defineConfig({
  plugins: [svelte(), svelteTesting()],
  test: {
    environment: 'jsdom',
    setupFiles: ['./src/test/setup.ts'],
    include: ['src/**/*.test.{ts,svelte.ts}'],
    coverage: {
      provider: 'v8',
      reporter: ['json'],
      reportsDirectory: './coverage/frontend',
      include: [
        'src/components/CuratedDataset.svelte',
        'src/components/OfflineComparisons.svelte',
        'src/components/LocalWidget.svelte',
        'src/components/WidgetSettings.svelte',
        'src/components/ActivitySummary.svelte',
        'src/components/AttentionSettings.svelte',
        'src/components/AttentionMonitor.svelte',
        'src/lib/stores/attention.ts',
        'src/components/ConvertedCost.svelte',
        'src/components/DiagnosticsPanel.svelte',
        'src/components/FxSettings.svelte',
        'src/components/IntegrationCenter.svelte',
        'src/components/SessionContextMenu.svelte',
        'src/components/SessionGridControls.svelte',
        'src/components/SessionProjectEditor.svelte',
        'src/components/TranscriptExport.svelte',
        'src/components/ProviderStatus.svelte',
        'src/components/TranscriptHandoff.svelte',
        'src/components/SessionOrganizationEditor.svelte',
        'src/components/OrganizationToolbar.svelte',
        'src/components/HumanOutcomes.svelte',
        'src/lib/humanOutcomes.ts',
        'src/lib/organization.ts',
        'src/lib/stores/organization.svelte.ts',
        'src/components/TranscriptSearch.svelte',
        'src/lib/configTimeline.ts',
        'src/lib/activitySummary.ts',
        'src/lib/defenderStatus.ts',
        'src/lib/diagnosticsExport.ts',
        'src/lib/flushCadence.ts',
        'src/lib/rangeData.ts',
        'src/lib/sessionGrid.ts',
        'src/lib/sessionExport.ts',
        'src/lib/stores/defender.svelte.ts',
        'src/lib/stores/projects.svelte.ts',
        'src/lib/stores/sessionDetailPane.svelte.ts',
        'src/lib/stores/sessionGrid.svelte.ts',
        'src/lib/trayTotals.ts',
        'src/lib/transcriptExport.ts',
        'src/lib/transcriptHandoff.ts',
      ],
    },
  },
});
