import { render, screen, waitFor } from '@testing-library/svelte';
import userEvent from '@testing-library/user-event';
import { beforeEach, expect, it, vi } from 'vitest';
import TranscriptExport from './TranscriptExport.svelte';
import type { TranscriptPage } from '../lib/types';
const mocks = vi.hoisted(() => ({ getTranscriptPage: vi.fn(), writeExport: vi.fn() }));
vi.mock('../lib/ipc', () => mocks);
const page: TranscriptPage = { provider: 'codex', availability: 'available', issues: [], next_cursor: null, source_complete: true, records: [{ id: 'one', byte_offset: 0, byte_length: 20, raw_json: 'Never export raw', kind: 'response_item', message_id: null, issue: null, presentation: { role: 'user', timestamp: null, blocks: [{ kind: 'text', text: 'Synthetic project private phrase', call_id: null, name: null, edit: null }] } }] };
beforeEach(() => {
  vi.resetAllMocks();
  mocks.getTranscriptPage.mockResolvedValue(page); mocks.writeExport.mockResolvedValue(true);
  Object.defineProperty(HTMLDialogElement.prototype, 'showModal', { configurable: true, value: function(this: HTMLDialogElement) { this.setAttribute('open', ''); } });
});
it('requires review and saves the exact sandboxed preview; option changes invalidate approval', async () => {
  render(TranscriptExport, { sessionId: 'synthetic', onclose: vi.fn() });
  expect(mocks.getTranscriptPage).not.toHaveBeenCalled();
  await userEvent.click(screen.getByRole('button', { name: 'Build preview' }));
  const save = await screen.findByRole('button', { name: 'Save reviewed HTML…' });
  expect(save).toBeDisabled();
  const frame = screen.getByTitle('Exact transcript export preview');
  expect(frame).toHaveAttribute('sandbox', '');
  const html = frame.getAttribute('srcdoc');
  await userEvent.click(screen.getByRole('checkbox', { name: /I reviewed every/ }));
  await userEvent.click(save);
  expect(mocks.writeExport).toHaveBeenCalledWith('odometer-transcript.html', 'html', html);
  await screen.findByText('Saved the exact preview to your selected file.');
  await userEvent.click(screen.getByRole('checkbox', { name: 'Tool results and errors' }));
  expect(screen.queryByTitle('Exact transcript export preview')).not.toBeInTheDocument();
  expect(screen.queryByRole('button', { name: 'Save reviewed HTML…' })).not.toBeInTheDocument();
  await userEvent.type(screen.getByRole('textbox'), 'private phrase');
  await userEvent.click(screen.getByRole('button', { name: 'Build preview' }));
  expect((await screen.findByTitle('Exact transcript export preview')).getAttribute('srcdoc')).not.toContain('private phrase');
  expect(screen.getByRole('checkbox', { name: /I reviewed every/ })).not.toBeChecked();
});
it('discards late source pages after cancellation or a session switch', async () => {
  let resolve!: (value: TranscriptPage) => void;
  mocks.getTranscriptPage.mockReturnValue(new Promise(done => { resolve = done; }));
  const view = render(TranscriptExport, { sessionId: 'synthetic', onclose: vi.fn() });
  await userEvent.click(screen.getByRole('button', { name: 'Build preview' }));
  await userEvent.click(screen.getByRole('button', { name: 'Cancel preview' }));
  resolve(page);
  await waitFor(() => expect(screen.queryByTitle('Exact transcript export preview')).not.toBeInTheDocument());
  mocks.getTranscriptPage.mockReturnValue(new Promise(done => { resolve = done; }));
  await userEvent.click(screen.getByRole('button', { name: 'Build preview' }));
  await view.rerender({ sessionId: 'different' });
  resolve(page);
  await waitFor(() => expect(screen.queryByTitle('Exact transcript export preview')).not.toBeInTheDocument());
});
it('reports missing source, save cancellation, and generic errors without leaking payloads or destinations', async () => {
  mocks.getTranscriptPage.mockResolvedValue({ ...page, records: [], source_complete: false, availability: 'missing' });
  render(TranscriptExport, { sessionId: 'synthetic', onclose: vi.fn() });
  await userEvent.click(screen.getByRole('button', { name: 'Build preview' }));
  await screen.findByText(/Incomplete source excerpt/);
  await userEvent.click(screen.getByRole('checkbox', { name: /I reviewed every/ }));
  mocks.writeExport.mockResolvedValue(false);
  await userEvent.click(screen.getByRole('button', { name: 'Save reviewed HTML…' }));
  await screen.findByText('Save cancelled.');
  mocks.writeExport.mockRejectedValue(new Error('PRIVATE_DESTINATION'));
  await userEvent.click(screen.getByRole('button', { name: 'Save reviewed HTML…' }));
  await screen.findByText(/The export could not be saved/);
  expect(screen.queryByText(/PRIVATE_DESTINATION/)).not.toBeInTheDocument();
  mocks.getTranscriptPage.mockRejectedValue(new Error('PRIVATE_SOURCE_BODY'));
  await userEvent.click(screen.getByRole('button', { name: 'Build preview' }));
  await screen.findByText(/Preview unavailable/);
  expect(screen.queryByText(/PRIVATE_SOURCE_BODY/)).not.toBeInTheDocument();
});
