// Browser-only canned responses generated by the production Rust query service.
// Range overlap is a synthetic fixture animation, not token/rate accounting.
import generated from './pricing.generated.json';
import type { PricedSurface, RangePricing, RateCard, Session, SessionPricing, SummaryPricing } from '../lib/types';

interface FixturePricing {
  summary: SummaryPricing;
  detail: SessionPricing;
  range: RangePricing;
}

const prices = generated.cases as Record<string, FixturePricing>;

function fixturePricing(key: string): FixturePricing {
  const value = prices[key];
  if (!value) throw new Error(`No Rust-generated browser pricing for fixture ${key}`);
  return structuredClone(value);
}

function scaleSurface(surface: PricedSurface, fraction: number): PricedSurface {
  return {
    ...surface,
    total: surface.total * fraction,
    by_model: surface.by_model.map(row => ({ ...row, cost: row.cost * fraction })),
  };
}

/** The mock distributes a fixture's already-priced total across its duration. */
export function mockRangePricing(key: string, fraction: number): RangePricing {
  if (!Number.isFinite(fraction) || fraction < 0 || fraction > 1) {
    throw new Error('Browser fixture range fraction must be between zero and one');
  }
  const value = fixturePricing(key).range;
  return {
    plan: scaleSurface(value.plan, fraction),
    api: value.api ? scaleSurface(value.api, fraction) : null,
  };
}

export function mockSummaryPricing(key: string): SummaryPricing {
  return fixturePricing(key).summary;
}

export function mockSessionPricing(key: string, session: Session): SessionPricing {
  const value = fixturePricing(key).detail;
  // Stress sessions reuse a fixture's exact monetary inputs, with new identities.
  const turns = Object.entries(value.turn_prices).sort(([a], [b]) =>
    Number(a.slice(a.lastIndexOf('-t') + 2)) - Number(b.slice(b.lastIndexOf('-t') + 2)));
  if (turns.length !== session.turns.length) throw new Error('Browser fixture turn shape changed; regenerate prices');
  value.turn_prices = Object.fromEntries(session.turns.map((turn, index) => [turn.turn_id, turns[index][1]]));
  return value;
}

function stableValue(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(stableValue).join(',')}]`;
  if (value && typeof value === 'object') {
    return `{${Object.entries(value).sort(([a], [b]) => a.localeCompare(b))
      .map(([key, entry]) => `${JSON.stringify(key)}:${stableValue(entry)}`).join(',')}}`;
  }
  return JSON.stringify(value);
}

/** Saving arbitrary monetary edits requires the native Rust backend. */
export function assertFixtureRates(rates: RateCard, original: RateCard): void {
  // These fields affect labels/settings only. Everything else must match the
  // card used by the generator, including future pricing fields by default.
  const presentation = new Set(['version', 'currency', 'currencies', 'source_url', 'fetched_at',
    'display_currency', 'subscription_plans']);
  const monetary = (value: RateCard) => {
    const normalized = { ...value,
      api_models: value.api_models ?? {},
      fallback_models: value.fallback_models ?? {},
      model_aliases: value.model_aliases ?? {},
      floating_model_aliases: value.floating_model_aliases ?? {},
      free_local_models: value.free_local_models ?? [],
      unpriced_models: value.unpriced_models ?? [],
    };
    return Object.fromEntries(Object.entries(normalized).filter(([key]) => !presentation.has(key)));
  };
  if (stableValue(monetary(rates)) !== stableValue(monetary(original))) {
    throw new Error('Browser fixtures use fixed Rust-generated prices. Edit pricing in the native app.');
  }
}
