import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';

import {
  VERSIONED_MANIFESTS,
  bumpCargoLock,
  bumpCargoToml,
  bumpPackageLock,
  bumpVersion,
  readManifestVersions,
  resolveNextVersion,
} from './bump-version.mjs';

const CARGO_TOML = `[package]
name = "agent-odometer"
version = "0.8.2"
edition = "2021"

[dependencies]
anyhow = "1"
version = "not-the-package-version"
`;

const CARGO_LOCK = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "adler2"
version = "2.0.1"

[[package]]
name = "agent-odometer"
version = "0.8.2"
dependencies = [
 "anyhow",
]

[[package]]
name = "anyhow"
version = "1.0.100"
`;

function withRepository(callback) {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'odometer-bump-version-'));
  try {
    fs.mkdirSync(path.join(directory, 'src-tauri'));
    const writeJson = (relativePath, value) => {
      fs.writeFileSync(path.join(directory, relativePath), `${JSON.stringify(value, null, 2)}\n`);
    };
    writeJson('package.json', { name: 'agent-odometer', version: '0.8.2', private: true });
    writeJson('package-lock.json', {
      name: 'agent-odometer',
      version: '0.8.2',
      lockfileVersion: 3,
      packages: {
        '': { name: 'agent-odometer', version: '0.8.2' },
        'node_modules/marked': { version: '0.8.2' },
      },
    });
    writeJson('src-tauri/tauri.conf.json', { productName: 'Odometer', version: '0.8.2' });
    fs.writeFileSync(path.join(directory, 'src-tauri/Cargo.toml'), CARGO_TOML);
    fs.writeFileSync(path.join(directory, 'src-tauri/Cargo.lock'), CARGO_LOCK);
    return callback(directory);
  } finally {
    fs.rmSync(directory, { recursive: true, force: true });
  }
}

test('resolves release kinds and explicit versions', () => {
  assert.equal(resolveNextVersion('0.8.3', 'patch'), '0.8.4');
  assert.equal(resolveNextVersion('0.8.3', 'minor'), '0.9.0');
  assert.equal(resolveNextVersion('0.8.3', 'major'), '1.0.0');
  assert.equal(resolveNextVersion('0.8.3', '0.8.4'), '0.8.4');
  assert.equal(resolveNextVersion('0.8.3', 'v0.9.0'), '0.9.0');
});

test('refuses versions that do not move forward', () => {
  assert.throws(() => resolveNextVersion('0.8.3', '0.8.3'), /must increase/);
  assert.throws(() => resolveNextVersion('0.8.3', '0.8.2'), /must increase/);
  assert.throws(() => resolveNextVersion('0.8.3', '0.9'), /MAJOR\.MINOR\.PATCH/);
});

test('rewrites only the [package] version in Cargo.toml', () => {
  const bumped = bumpCargoToml(CARGO_TOML, '0.8.4');
  assert.match(bumped, /\[package\]\nname = "agent-odometer"\nversion = "0\.8\.4"/);
  assert.match(bumped, /version = "not-the-package-version"/);
});

test('rewrites only the workspace crate entry in Cargo.lock', () => {
  const bumped = bumpCargoLock(CARGO_LOCK, '0.8.4');
  assert.match(bumped, /name = "agent-odometer"\nversion = "0\.8\.4"/);
  assert.match(bumped, /name = "adler2"\nversion = "2\.0\.1"/);
  assert.match(bumped, /name = "anyhow"\nversion = "1\.0\.100"/);
});

test('rewrites both project versions in package-lock.json but not dependencies', () => {
  withRepository((directory) => {
    const original = fs.readFileSync(path.join(directory, 'package-lock.json'), 'utf8');
    const lock = JSON.parse(bumpPackageLock(original, '0.8.4'));
    assert.equal(lock.version, '0.8.4');
    assert.equal(lock.packages[''].version, '0.8.4');
    assert.equal(lock.packages['node_modules/marked'].version, '0.8.2');
  });
});

test('bumps every release manifest to the same version', () => {
  withRepository((directory) => {
    assert.deepEqual(bumpVersion(directory, 'patch'), { current: '0.8.2', version: '0.8.3' });
    for (const [name, value] of Object.entries(readManifestVersions(directory))) {
      assert.equal(value, '0.8.3', `${name} was not bumped`);
    }
  });
});

test('leaves every manifest untouched when the requested version is rejected', () => {
  withRepository((directory) => {
    const before = VERSIONED_MANIFESTS.map((name) =>
      fs.readFileSync(path.join(directory, name), 'utf8'),
    );
    assert.throws(() => bumpVersion(directory, '0.8.1'), /must increase/);
    for (const [index, name] of VERSIONED_MANIFESTS.entries()) {
      assert.equal(fs.readFileSync(path.join(directory, name), 'utf8'), before[index]);
    }
  });
});

test('reads the real repository manifests as a single agreed version', () => {
  const versions = Object.values(readManifestVersions(process.cwd()));
  assert.equal(new Set(versions).size, 1, `manifests disagree: ${JSON.stringify(versions)}`);
});
